#python

SCENE_PATH = "scene"
FORMAT = "format"
FRAMES = "frames"
DESTINATION = "destination"
PATTERN = "suffix"
GROUPS = "passgroups"
WIDTH = "width"
HEIGHT = "height"
OUTPUTS = "outputs"
CAMERA = "camera"
STATUS = "status"
STATUS_COMPLETE = " (Complete)"
STATUS_IN_PROGRESS = " (In progress...)"