#python

SCENE_PATH = "scene"
FORMAT = "format"
FRAMES = "frames"
DESTINATION = "destination"
PATTERN = "suffix"
GROUPS = "passgroups"
WIDTH = "width"
HEIGHT = "height"
OUTPUTS = "outputs"
CAMERA = "camera"
RENDER_CHANNELS = "render_channels"
STATUS = "status"
STATUS_COMPLETE = "(Complete)"
STATUS_IN_PROGRESS = "(In progress...)"
STATUS_FAILED = "(Failed)"
STATUS_AVAILABLE = "(Available)"
TASK = "Task"
STATUS_FILE_SUFFIX = "status"